### ISSUE TITLE
repo rename and version mismatch

### ISSUE THREAD

**Issue by bosr** [conda-forge/tensorboardx-feedstock#6]
Hi, I noticed two small issues:
- in your `README.md` you still reference the previous name of the repo (was `tensorboard-pytorch`, now is `tensorboardX`
- in the tensorboardX repo, the latest release is 1.2: https://github.com/lanpa/tensorboardX/releases, but here you declare a 1.4.

**Comment by mdraw** [comment]
Thanks for reporting.
- I will fix the link in the readme with the next release (I think it's not urgent because https://github.com/lanpa/tensorboard-pytorch automatically redirects to https://github.com/lanpa/tensorboardX).
- Version 1.4 *is* released (see https://pypi.org/project/tensorboardX/1.4/), it's just not tagged in the git repo.

**Comment by bosr** [comment]
I agree, I reported it for the github.io page which does not redirect. 

Cheers,
Romain

**Comment by jakirkham** [comment]
Both of these appear to be resolved. Should this issue be closed?
